AllCops:
  EnabledByDefault: true
  Exclude:
    - vendor/**

Layout/LineLength:
  Enabled: true
  Max: 120

Style/DoubleQuotes:
  Enabled: true

Lint/EvalUsage:
  Enabled: true

Lint/UnusedVariable:
  Enabled: true
  IgnorePrefixedUnderscore: true
  IgnoreParameters: true

Metrics/AbcSize:
  Enabled: true
  Max: 17

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 7

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 8
